###
GET http://localhost:5000/api/goals/

###
GET http://localhost:5000/api/goals/200

###
POST http://localhost:5000/api/goals
content-type: application/json

{
    "text": "My Goal"
}

###
PUT http://localhost:5000/api/goals/200


###
DELETE  http://localhost:5000/api/goals/200